{
 "title": "API Logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request per Endpoint",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (endpoint) (\r\n  count_over_time({filename=\"/var/log/splice_api.log\"} | json [$__range])\r\n)"
    }
   ]
  },
  {
   "title": "Perecentage of requests made with DEX",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({filename=\"/var/log/splice_api.log\"} | json | platform=~\".*Python.*\" [24h]))\r\n/\r\nsum(count_over_time({filename=\"/var/log/splice_api.log\"} [24h])) * 100\r\n\r\n"
    }
   ]
  },
  {
   "title": "Total Jobs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Jobs Submitted" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by () (\r\n  count_over_time(\r\n    {filename=\"/var/log/splice_api.log\"} \r\n    | json \r\n    | endpoint=\"submit_job\" \r\n    | status_code=200\r\n    [$__range]\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Total Logins",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by () (\r\n  count_over_time(\r\n    {filename=\"/var/log/splice_api.log\"} \r\n    | json \r\n    | endpoint=\"login_for_access_token\" \r\n    | status_code=200\r\n    [$__range]\r\n  )\r\n)\r\n"
    }
   ]
  },
  {
   "title": "Requests per platform",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (platform) (\r\n  count_over_time({filename=\"/var/log/splice_api.log\"} | json [$__range])\r\n)"
    }
   ]
  }
 ]
}